stages:
  - test
  - release

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - node_modules

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.4.0
    inputs:
      image: registry.gitlab.com/thelabnyc/python:3.13.810-node20@sha256:021ab06d834d8a96fda03797b7b536cc77cfc31c86194a749a86a61c44936061

.base_job: &base_job
  image: node:22@sha256:9e6918e8e32a47a58ed5fb9bd235bbc1d18a8c272e37f15d502b9db9e36821ee
  before_script:
    - npm ci
  variables:
    NODE_ENV: development

test:
  <<: *base_job
  stage: test
  image: "${IMAGE}"
  script:
    - npm run lint
    - npm run build
    - npm run test
  parallel:
    matrix:
      - IMAGE: node:20
      - IMAGE: node:22

.release_job: &release_job
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
  stage: release
  needs:
    - test

release:pkg-npm:
  <<: *base_job
  <<: *release_job
  script:
    - echo "//registry.npmjs.org/:_authToken=${NPM_PUBLISH_TOKEN}" > .npmrc
    - npm run build
    - npm publish --access public

release:pkg-gitlab:
  <<: *base_job
  <<: *release_job
  script:
    - echo "@thelabnyc:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm run build
    - npm publish

release:gitlab:
  <<: *release_job
  image: registry.gitlab.com/gitlab-org/release-cli:latest@sha256:3f52d526f48e8d10625c722fa6d6423ee82aadeae1b1aa91f07b62551d96dacf
  script:
    - echo 'noop'
  release:
    name: "Release $CI_COMMIT_TAG"
    description: "Release $CI_COMMIT_TAG. Tagged by $GITLAB_USER_LOGIN"
    tag_name: "$CI_COMMIT_TAG"
    ref: "$CI_COMMIT_TAG"
